# .prettierrc.toml
plugins = ["@trivago/prettier-plugin-sort-imports"]
semi = true
importOrder = ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"]
importOrderSeparation = true,
importOrderSortSpecifiers = true