/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  containsBytes,
  getU8Encoder,
  Address,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  type ParsedAddToWhitelistInstruction,
  type ParsedCheckWhitelistedInstruction,
  type ParsedInitializeWhitelistInstruction,
  type ParsedRemoveFromWhitelistInstruction,
  type ParsedSetRateLimitingInstruction,
} from '../instructions';

export const NCN_PORTAL_PROGRAM_ADDRESS =
  'DwyMNTQ5aSduQhx3Pjra9kXeySxjD5YUkC1bDXmvEPFZ' as Address<'DwyMNTQ5aSduQhx3Pjra9kXeySxjD5YUkC1bDXmvEPFZ'>;

export enum NcnPortalAccount {
  Whitelist,
  WhitelistEntry,
}

export enum NcnPortalInstruction {
  InitializeWhitelist,
  AddToWhitelist,
  CheckWhitelisted,
  RemoveFromWhitelist,
  SetRateLimiting,
}

export function identifyNcnPortalInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): NcnPortalInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return NcnPortalInstruction.InitializeWhitelist;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return NcnPortalInstruction.AddToWhitelist;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return NcnPortalInstruction.CheckWhitelisted;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return NcnPortalInstruction.RemoveFromWhitelist;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return NcnPortalInstruction.SetRateLimiting;
  }
  throw new Error(
    'The provided instruction could not be identified as a ncnPortal instruction.'
  );
}

export type ParsedNcnPortalInstruction<
  TProgram extends string = 'DwyMNTQ5aSduQhx3Pjra9kXeySxjD5YUkC1bDXmvEPFZ',
> =
  | ({
      instructionType: NcnPortalInstruction.InitializeWhitelist;
    } & ParsedInitializeWhitelistInstruction<TProgram>)
  | ({
      instructionType: NcnPortalInstruction.AddToWhitelist;
    } & ParsedAddToWhitelistInstruction<TProgram>)
  | ({
      instructionType: NcnPortalInstruction.CheckWhitelisted;
    } & ParsedCheckWhitelistedInstruction<TProgram>)
  | ({
      instructionType: NcnPortalInstruction.RemoveFromWhitelist;
    } & ParsedRemoveFromWhitelistInstruction<TProgram>)
  | ({
      instructionType: NcnPortalInstruction.SetRateLimiting;
    } & ParsedSetRateLimitingInstruction<TProgram>);
